### ISSUE TITLE
Test Component, ComponentParameter, Engineer and Manager REST endpoints

### ISSUE THREAD

**Issue by elderanakain** [elderanakain/pa165-formula-one-team#100]
- [x] `Component` endpoint works fine and is able to apply CRUD requests.
- [x] `ComponentParameter` endpoint works fine and is able to apply CRUD requests.
- [x] `Engineer` endpoint works fine and is able to apply CRUD requests and auth/register.
- [x] `Manager` endpoint works fine and is able to apply CRUD requests and auth/register.

If you find a bug, please, create a new issue with a description.

**Comment by mrnustik** [comment]
@elderanakain this can be closed.
