### ISSUE TITLE
Component not deleted when parameters are present

### ISSUE THREAD

**Issue by mrnustik** [elderanakain/pa165-formula-one-team#102]
Component are causing constraint validation exception on delete (cascading is not setup)

In sample data do:
DELETE - https://localhost:8080/pa165/rest/1

**Comment by mrnustik** [comment]
@elderanakain can it happen in our system that two components share one parameter?

**Comment by mrnustik** [comment]
@elderanakain also there is a question whether component should be removable when it is a part of car setup?

**Comment by elderanakain** [comment]
@mrnustik Sorry, for the late reply.
1) No, let's keep them separated. Even, if we have the same value and name, there is no need to share it with others.
2) I would say - no. A car setup is just a set of components and components can exist without it.

**Comment by mrnustik** [comment]
@elderanakain Hopefully last question for this issue:
If Component is part of CarSetup and i try to delete that Component should there be an exception thrown?

**Comment by elderanakain** [comment]
@mrnustik 
Yes, because first, we need to delete a car setup, because we cannot have a car without one component.
I think an explicit exception should be thrown on facade layer.
