### ISSUE TITLE
Component parameter update

### ISSUE THREAD

**Issue by elderanakain** [elderanakain/pa165-formula-one-team#127]
Bug:
- [x] Component parameters are not updated via web.

**Comment by elderanakain** [comment]
@mrnustik Could you check it this bug on web part?
I have tried to fix it, but I could only remove throwing a JPA exception, but the update doesn't still work.
I think we can leave it for M4, but if you have time now it would be better.

**Comment by mrnustik** [comment]
I will look onto it.
