### ISSUE TITLE
Create base REST controller test

### ISSUE THREAD

**Issue by elderanakain** [elderanakain/pa165-formula-one-team#92]
- [ ] Contains `create*` method which provides a new instance of an entity.
- [ ] Contains `ObjectMapper` initialization.
- [ ] Contains `MockMvc` initialization in `@Before` method which uses `protected abstract` method with provided `controller` object.
- [ ] Contains `MockitoRule ` initialization.
- [ ] Contains test annotations.
- [ ] `extends AbstractTestNGSpringContextTests`.

**Comment by mrnustik** [comment]
If we are going to use mocks of facade we won't need the last two bullets.
