### ISSUE TITLE
Drivers pages

### ISSUE THREAD

**Issue by elderanakain** [elderanakain/pa165-formula-one-team#94]
- [x] `Drivers` button in the navigation bar leads to a page with a list of drivers.
- [x] The list of drivers has columns: `Name` (name+surname), `E-mail`, `Status`, `Current races`
- [x] `Current races` column has a list of races in which the current driver is participating right now. Each race should be clickable and should lead to a detail page of the race (if a detail page is not implemented, just a mock-up link to 404).
- [x] All column names should be clickable. As soon as one of them is clicked - the list is sorted by this value. For the `Current races`, it should just compare a number of races not races themselves.
- [x] Each row of the list is selectable (changes the background when a mouse cursor is above) and clickable, and navigates to a detail page of the driver.
- [x] The detail page shows the full information about the driver in `key`: `value` way in one column. It includes all field of the entity without `password`. Then other information where the driver is mentioned - characteristics, race participation list and test drives. For now, it should look like simple lists, however, it will do a cross-reference to reuse a design from the corresponding pages.
- [x] The list of drivers page should contain a button `Add` or a plus sign icon button below the title. This button leads to a page with a form for creating a new driver.
- [x] The new driver form should have `Name`, `Surname`, `E-mail`, `Password`, `Password confirmation`, `Nationality`, `Birthday`, `Driver status` (a dropdown list) and `Characteristics` fields.
- [x] `Characteristics` field should have 3 rows and 2 columns, where the first column is a drop-down list with`CharacteristicsType` and the second one is a numeric value.
- [x] All fields check should be consistent with the entity columns constraints. For example, `name` cannot be empty and null, but `characteristics` can be empty list.
- [x] At the bottom of the page, there is a `Add` button.
- [x] After a driver successfully added, the user is redirected to the list of drivers.
- [x] On details of a driver page, there is a button `Update` or a pencil icon button, which leads to a update page. It should look and behave the same as the new page, but with prefilled data. (please, reuse code)

**Comment by mrnustik** [comment]
Currently waiting for #90.

**Comment by elderanakain** [comment]
@mrnustik #90 is merged. Could you provide an estimation for this task - which date?

**Comment by mrnustik** [comment]
@elderanakain tomorrow afternoon it should be ready.

**Comment by elderanakain** [comment]
@theodesjardins Please, track the future PR for drivers, because you have similar functionality.

**Comment by mrnustik** [comment]
@theodesjardins I hope I will finish today if I won't be able to you can track the progress in my PR #110.

**Comment by theodesjardins** [comment]
@mrnustik Ok I will start like that, just tell me when your work is merged so I could pull the last version of `develop` ;)

**Comment by mrnustik** [comment]
@theodesjardins done.
